import 'ngreact';
export {default as AngularProvider} from './provider';
export {default as $inject} from './inject';
export {default as $resolve} from './resolver';
export {default as compose} from './compose';
export {default as watch} from './watch';
export {default as apply} from './apply';
export {default as registerReactComponent} from './register';
export {default as registerReactRouteComponent} from './registerRoute';
export {default as forRouter} from './forRouter';
