import 'ngreact';
export {default as AngularProvider} from './provider';
export {default as withInjector} from './injectorProvider';
export {default as withScope} from './scopeProvider';
export {default as $inject} from './inject';
export {default as $resolve} from './resolver';
export {default as watch} from './watch';
export {default as compose} from './compose';
export {default as reactify} from './reactify';
export {default as registerReactComponent} from './register';
export {default as forRouter} from './forRouter';
